spring:
  application:
    name: Currency-Converter

rest:
  currency-layer:
    api-key: d0f9ac679bbb43417768123ff2170531
    url: https://api.currencylayer.com
    connect-timeout: 60000
    read-timeout: 60000
